import { Lato } from "next/font/google";
import { Navbar } from "./components/navbar/navbar";
import "./globals.css";
import AuthProvider from "./context/authProvider";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <AuthProvider>
          <main className="w-full lg:w-8/12 md:w-9/12 m-auto">
            <Navbar />
            <div className="px-4">{children}</div>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
